# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

        # 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not 
# exceed four million, find the sum of the even-valued terms.

def fib(num1):
    for x in range(num1):
        if num1 == 0:
            return 1
        if num1 == 1:
            return 2
        else:
            return fib(num1 - 1) + fib(num1 - 2) 


if __name__ == "__main__":
    num1 = fib(1)
    print(num1)